### ISSUE TITLE
Remove hardcoded strings in InitalizationUtil

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#296]
In anroidlibrary the file InitializationUtil has hardcoded strings "csv" and "properties" that should be abstracted to a string constant.

**Comment by chitranshix** [comment]
Hi! I'm Chitranshi Srivastava from India. I have experience in developing Android apps in Kotlin & JAVA. I am an Outreachy applicant in the pre-proposal stage. I want to contribute to ODK-X by "Updating ODK-X’s Tests to most recent Android Testing Framework." Kindly assign me this issue so that I can start contributing.

**Comment by elmps2018** [comment]
Hi @apigeoneer! I have assigned this to you! Please let us know any questions as you work away.

**Comment by chitranshix** [comment]
Thanks! I've made a PR, kindly review it.
