### ISSUE TITLE
Redesign form navigation for ODK-X Survey

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#359]
The navigation between forms pages in ODK-X Survey is not well presented, and does not fit long form names well. 

![Screen Shot 2022-10-01 at 13 52 27](https://user-images.githubusercontent.com/1215441/193394850-4cff4f80-f947-4999-aa98-83e9f504a589.png)

## Why this needs to be improved:
- Long form names do not fit in the button
- The layout 'breaks' on some devices
- The design can be updated in line with the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

## Guidance for this issue:
- Familiarize yourself with Survey navigation within a form
- Provide a redesign of the navigation that improves on the issues above
- Write a brief description including a rationale for the design that you applied
- Post the description and screenshots back to this issue

## Design Guidelines:
Colours, icons and other user interface elements used should conform to the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

## Outreachy
This issue can be used for an Outreachy application for the project [Custom UI components for ODK-X mobile apps](https://www.outreachy.org/apply/project-selection/#odk-x)
**This issue is for the User Interface Design stream of the project.**

Multiple people can work on this issue simultaneously.

**Comment by phelisa1** [comment]
Hello again @maprehensive, may I please work on this issue?

**Comment by maprehensive** [comment]
@phelisa1 Yes, but I'll assign after you've completed https://github.com/odk-x/tool-suite-X/issues/366. Thanks :)

**Comment by cvemann** [comment]
Same here @maprehensive since multiple people can work on this issue.

**Comment by EQua-Dev** [comment]
Hi @maprehensive, please can I be assigned this task?

**Comment by Augusta2** [comment]
Hello @maprehensive  Can I work on this task?

**Comment by Pamela-owino** [comment]
Hello @maprehensive, can I please work on this issue?

**Comment by cvemann** [comment]
Hello @maprehensive 

This is the redesign that improves on the issues above.

<img width="434" alt="Navigation Form" src="https://user-images.githubusercontent.com/80982139/194803633-3ad0d23b-bff8-44a6-a9bc-237fc2bc3d92.png">

Here are my reasons for this redesign:

- I used ellipsis to hide the remaining characters in long form names.
- I also used the tint blue hue #E7EEF6 has the background for the Top Bar
- The navigations are also placed in auto layouts to make them fluid and responsive across any device. They won't have to 'break' again.
- I also followed the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/edit#slide=id.ge77e0fa0bd_0_0)

**Comment by maprehensive** [comment]
@Augusta2 and @Pamela-owino you're assigned. Thank you!

**Comment by BlueSkiez-dev** [comment]
@maprehensive I'd like to work on this issue...

**Comment by BlueSkiez-dev** [comment]
Hi @maprehensive 
The best way around this issue is to make the view responsive.
Trying to compress the components on one line will cause a layout break, and truncating the text on the form title will cause informative issues. So the goal is to break the line and use the available space on smaller screens

My Solution to this issue is as follows:

![ezgif-1-e3acb0b9a8](https://user-images.githubusercontent.com/67054844/194844317-1561ee92-1e3d-40cb-97f4-28b3e04910d3.gif)


<img width="863" alt="Frame 12 (1)" src="https://user-images.githubusercontent.com/67054844/194847945-f473f7a5-29a0-4d0f-b407-a665804ea72e.png">

**Comment by cvemann** [comment]
Hello @maprehensive, In contribution to creating custom UI components for ODK-X Apps, I made an improvement to the form navigation I designed earlier. See:

![image](https://user-images.githubusercontent.com/80982139/195233450-2751df72-d770-4f85-9ee8-aa14a4025d7f.png)

**Description;**
It has...
- a well designed top bar which contains the title (22px) for the current survey form.
- a colour fill of #E7EEF6 as seen in the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/edit#slide=id.g15bd994772e_0_3), to separate it from the form content below.
- a width that stretches across the width of the screen and is  also responsive.

This way,
- Longer form names can be shown.
- The layout would remain consistent across devices.

My design follows the established 8-point grid system with a 24px on all sides.

Please let me know if this works. Thank you

**Comment by G-ann** [comment]
Hello, can I be assigned to this issue, I would love to contribute.

**Comment by jessjaey** [comment]
@maprehensive Can I be assigned this issue??

**Comment by mishymia** [comment]
Hi @maprehensive can I be assigned to this issue?

**Comment by Daveojoe** [comment]
Hi, @maprehensive can I be assigned to this issue?

**Comment by maprehensive** [comment]
@G-ann @jessjaey @mishymia @Daveojoe Yes please go ahead and work on it. You no longer need to be assigned to the issue. Thanks!

**Comment by jessjaey** [comment]
@maprehensive  worked on this issue and I would appreciate your feedback on this.
Thankyou ![image](https://user-images.githubusercontent.com/105664383/195714985-becace8c-9f54-4f47-adf4-57b6b1dae6a2.png)

**Comment by caxrii** [comment]
@maprehensive I'd like to work on this

**Comment by Augusta2** [comment]
Hello @maprehensive 
Hope your day is going well?

This is my contribution on this issue.


The users I asked to check out the App did not notice that the Button holding the form name was clickable, therefore, they missed whatever information they would have gotten from it. 
I think we should solve the issue of the Form navigation and also find a way to make the other information reachable and more noticeable by the users.

![survey redesign1](https://user-images.githubusercontent.com/115414092/196039877-59f5df0d-7424-4106-a952-5ba31c2df74a.png)
![Survey Redesign 2](https://user-images.githubusercontent.com/115414092/196039888-ee0ce1ee-83b5-4e5d-9159-836dbe5276ab.png)

The design of the 'floating action button' is inspired by the shape of the letter O in the ODK-X logo.

![Survey form1](https://user-images.githubusercontent.com/115414092/196040038-d090ae0a-d3c8-45f1-ad27-e40b68c91e64.png)
![Survey form 2](https://user-images.githubusercontent.com/115414092/196040049-b8b94d22-7840-49e6-8652-bf14ac4f7b17.png)

![survey form overlay](https://user-images.githubusercontent.com/115414092/196039896-ef235db9-ac78-4d5d-90ca-c7beeda6d990.png)
![Survey form gif](https://user-images.githubusercontent.com/115414092/196049426-ffc95376-bb54-41fd-8943-62708f9b24b2.gif)

![XRecorder_16102022_181604_1](https://user-images.githubusercontent.com/115414092/196049409-08e66cde-8905-4a8d-9355-54a8f7071028.gif)

![Augusta_Recommendations](https://user-images.githubusercontent.com/115414092/196050375-28cfa66c-92ff-4e4e-85b3-11dbb3295607.png)




This is the link to the[ prototype on Figma](https://www.figma.com/proto/acrU99IH3PedOPYpaN4jnT/Untitled?node-id=227%3A174&scaling=scale-down&page-id=71%3A95&starting-point-node-id=206%3A429&show-proto-sidebar=1)

**Comment by caxrii** [comment]
![Light](https://user-images.githubusercontent.com/99927193/196046442-91ac5362-0553-4a6f-b37a-a58e30aeedb5.png)
![Light 1](https://user-images.githubusercontent.com/99927193/196046436-b9652ebe-afb7-434b-a981-a1cc262f1db6.png)
![Light 2](https://user-images.githubusercontent.com/99927193/196046440-ad9e4f5e-4030-41b1-8c5b-246f943b4b8e.png)
![Light 3](https://user-images.githubusercontent.com/99927193/196046441-d2ad29bc-992a-4b2a-9353-7b25cc76a437.png)
![Dark](https://user-images.githubusercontent.com/99927193/196046457-f6f6d47e-3c4a-4f6d-bd8b-bf89f14450f5.png)
![Dark 1](https://user-images.githubusercontent.com/99927193/196046453-ef39f70b-ca7d-4d5f-8204-4e0e9a026290.png)
![Dark 2](https://user-images.githubusercontent.com/99927193/196046455-178c3bb9-8d46-4b25-81ad-3c3321c398f5.png)
![Dark 3](https://user-images.githubusercontent.com/99927193/196046456-17db663e-04c9-46fe-be04-7b2920e463c5.png)


@maprehensive
 
1. I did a few designs for the navigation in light and dark theme mode. Reason for this was to check for accessibility.
2. I used the chevron icons to indicate next and previous to allow The headings have more room and negative space to breathe.
3. I added a text to the second design to indicate progress as the user fills the survey forms.
4. In the Third design i felt a progress bar should indicate the users progress.
5. In the Fourth design i used the progress bar and a text below to indicate progress.

I'd love to here your feedback on this, Thanks.

**Comment by IjeomaGeorge** [comment]
Hi @maprehensive I redesigned the issue on The navigation between forms pages in ODK-X Survey,
1. I used the eclips on the household survey button just as @Cveman1 which suggests that the button has more character after the household; this allows for the button's simplicity and neatness.
2. Knowing well well that ODK-X App has both a dark and a bright mode, I also created a dark mode for it because it's best to always create both when rebuilding any. 
![Screen Shot 2022-10-18 at 9 18 2](https://user-images.githubusercontent.com/81042220/196378568-8926f1ab-0275-40b0-98c7-5344dba310a2.png)

**Comment by mishymia** [comment]
Hi @maprehensive 
The goal is to make longer names fit so it doesn't break out on some devices
Here's my idea and reasons for the redesign.
- The button that contains "Household survey", I added a drop-down icon to clearly indicate that it is a button.
- I increased the spacing between text and the icon (48px maintaining the 8pt grid system of the guidelines), doing so it can contain longer texts and doesn't break out.
- I placed the "Next" button at the downright corner of the screen to create breathing space in the top navigation bar.
- Lastly, I retained the regular position of the back button since that's what users are used to, while I brought the next button down so it's easier to go forward.
![Android Large - 2.png](https://user-images.githubusercontent.com/105456703/196890674-278f9023-7e5b-4680-81fa-210ab232b73c.png)

**Comment by Rubadel** [comment]
I design this layout, (I try more than one for search design)

<img width="310" alt="Screen Shot 1444-03-24 at 2 41 38 AM" src="https://user-images.githubusercontent.com/66481905/196824907-05518198-ff14-43c0-b029-0b1db173c283.png">

<img width="315" alt="Screen Shot 1444-03-24 at 2 43 12 AM" src="https://user-images.githubusercontent.com/66481905/196824915-c214100a-72a0-455b-82cf-780550633bb8.png">

<img width="332" alt="Screen Shot 1444-03-24 at 2 41 59 AM" src="https://user-images.githubusercontent.com/66481905/196824953-e61f8850-19ac-4bdf-858c-09157e42ee8d.png">

<img width="311" alt="Screen Shot 1444-03-24 at 2 42 46 AM" src="https://user-images.githubusercontent.com/66481905/196824966-a50c3531-3aae-432b-a20d-752569c1c54e.png">

<img width="308" alt="Screen Shot 1444-03-24 at 2 42 21 AM" src="https://user-images.githubusercontent.com/66481905/196825004-b41ed1ce-dd30-45f7-89f3-bc4309edb280.png">

<img width="316" alt="Screen Shot 1444-03-24 at 2 47 21 AM" src="https://user-images.githubusercontent.com/66481905/196825126-a35df129-3a6b-46cd-92ca-b47f4a22454d.png">


Features of my opinion:
-The main problem of Long form names is solved and in all device.
- Made navigation most easy, that it show all surevys in list so user can browse them quickly and take overview, rather than show one by one.
- Enabled the search, so if they are so many the search will help ( I recommend to activation the search within title and content by coding) .
- Simple and more comfortable/familiar for all users.

**Comment by salmasabo** [comment]
![image](https://user-images.githubusercontent.com/115367130/197265522-2113e492-f577-4bac-b026-89abcb44818d.png)
@maprehensive 
1.I placed the navigations in auto layout so it's scalable and responsive across all devices. 

2.I chose chevron icons to indicate back and forth as they are the modern icons used to depict that.

3.also added numeric progress to indicate progress as users fill the form.

**Comment by Karimatu05** [comment]
Hello @maprehensive what do you think on this please, looking forward to see your feedback thank you 
![Household Survey](https://user-images.githubusercontent.com/100648626/197306622-8b96a728-349a-49c7-bc9b-ac42ccd40e8e.jpg)

**Comment by JessicaItepu** [comment]
..

**Comment by designita** [comment]
@maprehensive Here is my contribution to the above stated issue, I'd appreciate your review.
![Screenshot (3)](https://user-images.githubusercontent.com/99173516/199224038-922f79f9-3604-4a9d-a315-d962aaff7be6.png)
![Screenshot (1)](https://user-images.githubusercontent.com/99173516/199224109-97a6222e-a277-4402-9ef7-bcea432d04c3.png)
![Group 1](https://user-images.githubusercontent.com/99173516/199225049-9ccb64ad-542c-4488-a261-6720a2e630ec.png)

**Comment by Redeem-Grimm-Satoshi** [comment]
**Form Navigation Redesign**
----------------------------------------------------------------------------------
![Google Pixel 6 Pro – 1@3x](https://user-images.githubusercontent.com/45304978/199310646-d7024100-a07a-40e3-b661-882d3818b82d.png)
------------------------------------------------------------------

**##This is modern and minimalist design.**
1. Long form names will be able to fit in since the button's width matches the parent container and a horizontal margin of 4dp /px was applied.
2. Layout won't break on smaller devices since the button's width increases/reduces depending on the device screen size
3. User can input a page number and skip to the page directly ( for a great user experience )
4. Material design icon used ( free to use )
5. Design falls inline with the ODK-X design guidelines. 

@maprehensive I'll happy to receive a feedback from you.

**Comment by Pamela-owino** [comment]
Hi @maprehensive This is my redesign proposal 
1 declutter the navigation bar and make it more cleaner. 
2. The back and next icons are well known and therefore do not need labels. 
3. Include page numbers to make it easy for the user to navigate through pages. 
![Screenshot 2022-11-01 23 31 48](https://user-images.githubusercontent.com/115387068/199335766-491fabdf-f8d9-47b8-b729-2953d554177f.png)

**Comment by 010220010** [comment]
Hello @maprehensive, this is to present to you my redesign for the flagged issue to meet the set objectives following the approve style guides. Please do well to review it and let me know your thought on it, thank you.

![DESCRIPTION](https://user-images.githubusercontent.com/105234341/199612987-e1ce2c83-8975-45c5-9619-b4d4d5eb19b3.png)

**Comment by Erieola** [comment]
Hello @maprehensive here's my contribution to this task.

![Form Navigation](https://user-images.githubusercontent.com/81233753/199732634-ae3217fb-f7d2-4521-af4a-9ba59c32adeb.png)

Figma link: https://www.figma.com/file/unVUG3yR0McIsDeeqPrtrO/Erie?node-id=43%3A7373

**Comment by cvemann** [comment]
Hi @Redeem-Grimm-Satoshi. Following the top app bar solution in #397, here's a redesign for the form navigation for ODK-X Survey. 

Users no longer need to tap the name of the form to reveal the menu that provides navigation and exit options. This wasn't so intuitive. It now overflows into the 3 dot menu, following the specs for [Materials' Top App Bar](https://m3.material.io/components/top-app-bar/specs).

![Image](https://user-images.githubusercontent.com/80982139/213804791-52ce0ba6-b62b-4c89-8971-c8abc758cd5f.png)

###Guidance
1. The Top App Bar follows the guidelines here #397
2. The card containing the information about the form should conform to the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/edit#slide=id.g14253eab164_0_0)
3. The buttons follow the guidelines in #402 

What do you think @maprehensive

**Comment by syedbarimanjan** [comment]
I would like to work on this!

**Comment by medinasheriff** [comment]
![Image](https://github.com/odk-x/tool-suite-X/assets/98324163/8c9daef8-bcd8-4555-be1a-beae98f5452b)

**Comment by medinasheriff** [comment]
![Image](https://github.com/odk-x/tool-suite-X/assets/98324163/3c78e7b3-8408-4f6f-9a5d-9d5a95ce2807)

Hello @maprehensive, I'm an Outreachy applicant. Since you've said we can just jump into tackling an issue without being assigned. I decided to try with this. 

BUTTONS: I noticed everyone has tried to stick with the Back, and Next buttons being side by side, but I checked and there's no instruction stating it absolutely has to be that way, so I placed the text field between them.

Thoughts: I believe having the text field between them is better for user experience due to the distance between the 2 buttons, and also positioning sort of just lets you know the direction youre going.

I also made them TEXT buttons because, this makes it look less clustered.

TEXT FIELD: Following the ODK-X design guide, the text field had to be a specific size, the specified size wouldn't allow long survey names to show in full, so I introduced a truncating effect where the rest of the text is clipped when maximum text capacity is reached.

I introduced an overlay which shows the full text, and extends vertically for really long survey names once the textfield is touched, this allows users to see and read full text at once instead of only having to scroll inside the text box.

All text and colours adhere to the provided ODK-X design guidelines.

**Comment by medinasheriff** [comment]
![Image](https://github.com/odk-x/tool-suite-X/assets/98324163/16e08aed-6047-41cf-8be3-3a424ffb3e51)

@maprehensive @Redeem-Grimm-Satoshi  I noticed an issue with the design guidlines, the colour code given for the "bg for forms/sections #E8EEF6" for dark mode is wrong, its the same as the code for the white background. I'm bringing this to you as an added issue albeit a small one. It could affect the uniformity of designed dark mode screens.

**Comment by medinasheriff** [comment]
@maprehensive Here is the link to a new issue I created for the design guidelines https://github.com/odk-x/tool-suite-X/issues/489
